# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "otab-grub"
BBFILE_PATTERN_otab-grub = "^${LAYERDIR}/"
BBFILE_PRIORITY_otab-grub = "1"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_otab-grub = "1"

LAYERDEPENDS_otab-grub = " \
    otab-common \
    core \
    openembedded-layer \
    swupdate \
    "

LAYERSERIES_COMPAT_otab-grub = "honister kirkstone mickledore master"

##################################################
# OTAB variables
##################################################

WKS_FILE:qemux86-64 = "otab-grub-x86uefi.wks.in"
WKS_FILE:vbox = "otab-grub-x86uefi.wks.in"
GRUB_EFI_DIR = "EFI/BOOT"
IMAGE_BOOT_FILES = " \
    grub.cfg;${GRUB_EFI_DIR}/grub.cfg \
    grubenv;${GRUB_EFI_DIR}/grubenv \
    grub-efi-bootx64.efi;${GRUB_EFI_DIR}/bootx64.efi \
    bzImage-initramfs-${MACHINE}.bin;bzImage-initramfs-a \
    bzImage-initramfs-${MACHINE}.bin;bzImage-initramfs-b \
    "

OTAB_DEVICE_MAIN ?= "/dev/sda"
OTAB_DEVICE_BOOT ?= "${OTAB_DEVICE_MAIN}1"
OTAB_DEVICE_ROOTFS_A ?= "${OTAB_DEVICE_MAIN}2"
OTAB_DEVICE_ROOTFS_B ?= "${OTAB_DEVICE_MAIN}3"

OTAB_SERIAL_CONSOLE ?= "ttyS0,115200n8"
