#!/bin/sh

error_check() {
    ret=$?
    err_msg="$1"
    if [ $ret != 0 ]; then
        fatal "$err_msg (err=$ret)"
    fi
}

create_overlay_enabled() {
	return 0
}

# create rwoverlay partition on first boot.
create_overlay_run() {
    partition="/dev/disk/by-partlabel/<OTAB_LABEL_ROOTFS_OVERLAY>"
    if [ -b "$partition" ]; then
        return 0
    fi
    # shellcheck disable=SC3040
    set -o pipefail
    disk="$(lsblk -no pkname "/dev/disk/by-partlabel/<OTAB_LABEL_ROOTFS_A>")"
    echo "Creating <OTAB_LABEL_ROOTFS_OVERLAY> partition"
# 1st - create new partition, use recommended values
# 2nd - set partlabel of last (default) partition to <OTAB_LABEL_ROOTFS_OVERLAY>
    fdisk "/dev/$disk" <<EOF >/dev/null
n



x
n

<OTAB_LABEL_ROOTFS_OVERLAY>
r
w
EOF
    error_check "Failed to create new partition on /dev/$disk"
    sleep 2
    mkfs.ext4 -qFL "<OTAB_LABEL_ROOTFS_OVERLAY>" "$partition" >/dev/null
    error_check "Failed to create ext4 filesystem on $partition"
    # shellcheck disable=SC3040
    set +o pipefail
}
