check_keyslots() {
    luks_dump="$1"
    jq_arg='
    {
        tpm_keyslots: [.tokens[] | select((.type == "systemd-tpm2") or (.type == "systemd-recovery")) | .keyslots[]],
        all_keyslots: [.keyslots | keys[] | tonumber]
    } | select(((.all_keyslots | length) - (.tpm_keyslots | length)) != 0) | error("Not all keyslots use TPM2 or recovery key")
    '
    echo "$luks_dump" | jq "$jq_arg"
}

check_keyslot_at_least_one() {
    luks_dump="$1"
    type="$2"
    jq_arg="
    [.tokens[] | select(.type == \"${type}\") | .keyslots[]] | select(length == 0) | error(\"No ${type} keyslots used\")
    "
    echo "$luks_dump" | jq "$jq_arg"
}

df_source() {
    df "$1" --output=source 2>/dev/null | sed 1d
}

realpath_df_source() {
    realpath "$(df_source "$1")" 2>/dev/null
}

get_swupdate_default_bootloader() {
    temp=$(mktemp)
    swupdate -vnci "$temp" 2>&1 | grep -o "Using default bootloader interface:.*" | sed 's/.*: //'
    rm "$temp"
}

test_partition() {
    part_device="$1"
    part_name="$2"

    cukinia_log "Test ${part_name}"
    if as "Check if ${part_device} is encrypted" cukinia_cmd cryptsetup status "${part_device}";
    then
        encrypted_device=$(cryptsetup status "${part_device}" | sed -n "s|.*device:.*\(/dev/.*\)|\1|p")
        luks_dump=$(cryptsetup luksDump "${encrypted_device}" --dump-json-metadata 2>/dev/null)
        ret=$?
        if as "Check if we can get rootfs LUKS device information dump" cukinia_test $ret -eq 0;
        then
            as "Check if rootfs can only be decrypted with TPM2 or recovery key" cukinia_cmd check_keyslots "${luks_dump}"
            as "Check if rootfs can be decrypted via TPM2" cukinia_cmd check_keyslot_at_least_one "${luks_dump}" "systemd-tpm2"
            as "Check if rootfs can be decrypted via recovery key" cukinia_cmd check_keyslot_at_least_one "${luks_dump}" "systemd-recovery"
        fi
    fi
}

section "Encryption feature"

current_part_var="$(fw_printenv otab_part_current | sed -r 's/.*=(.*)/\1/')"
rootfs_part_a="/dev/disk/by-label/<OTAB_LABEL_ROOTFS_A>"
rootfs_part_b="/dev/disk/by-label/<OTAB_LABEL_ROOTFS_B>"
overlay_part="/dev/disk/by-label/<OTAB_LABEL_ROOTFS_OVERLAY>"

if [ "${current_part_var}" = "A" ]; then
    current_part="${part_a}"
    next_part="${part_b}"
    next_part_var="B"
elif [ "${current_part_var}" = "B" ]; then
    current_part="${part_b}"
    next_part="${part_a}"
    next_part_var="A"
fi

test_partition "${rootfs_part_a}" "rootfs partition A"
test_partition "${rootfs_part_b}" "rootfs partition B"
test_partition "${overlay_part}" "rootfs overlay partition"
