source "$(dirname "${BASH_SOURCE[0]}")/encryption-common.sh"

get_swupdate_default_bootloader() {
    temp=$(mktemp)
    swupdate -vnci "$temp" 2>&1 | grep -o "Using default bootloader interface:.*" | sed 's/.*: //'
    rm "$temp"
}

section "Encryption feature"

current_part_var="$(fw_printenv otab_part_current | sed -r 's/.*=(.*)/\1/')"
rootfs_part_a="/dev/disk/by-label/<OTAB_LABEL_ROOTFS_A>"
rootfs_part_b="/dev/disk/by-label/<OTAB_LABEL_ROOTFS_B>"
overlay_part="/dev/disk/by-label/<OTAB_LABEL_ROOTFS_OVERLAY>"

if [ "${current_part_var}" = "A" ]; then
    current_part="${part_a}"
    next_part="${part_b}"
    next_part_var="B"
elif [ "${current_part_var}" = "B" ]; then
    current_part="${part_b}"
    next_part="${part_a}"
    next_part_var="A"
fi

test_partition "${rootfs_part_a}" "rootfs partition A"
test_partition "${rootfs_part_b}" "rootfs partition B"
test_partition "${overlay_part}" "rootfs overlay partition"
