# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILES_DYNAMIC += " \
    raspberrypi:${LAYERDIR}/dynamic-layers/raspberrypi/recipes-*/*/*.bb \
    raspberrypi:${LAYERDIR}/dynamic-layers/raspberrypi/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "otab-rorootfs"
BBFILE_PATTERN_otab-rorootfs = "^${LAYERDIR}/"
BBFILE_PRIORITY_otab-rorootfs = "13"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_otab-rorootfs = "1"

LAYERDEPENDS_otab-rorootfs = " \
    otab-common \
    core \
    openembedded-layer \
    readonly-rootfs-overlay \
    otab-uboot \
    "

LAYERSERIES_COMPAT_otab-rorootfs = "honister kirkstone master"
