section "A/B feature"

df_source() {
    df "$1" --output=source 2>/dev/null | sed 1d
}

realpath_df_source() {
    realpath "$(df_source "$1")" 2>/dev/null
}

get_swupdate_default_bootloader() {
    temp=$(mktemp)
    swupdate -vnci "$temp" 2>&1 | grep -o "Using default bootloader interface:.*" | sed 's/.*: //'
    rm "$temp"
}

current_part_var="$(fw_printenv otab_part_current | sed -r 's/.*=(.*)/\1/')"
part_a="/dev/disk/by-label/<OTAB_LABEL_ROOTFS_A>"
part_b="/dev/disk/by-label/<OTAB_LABEL_ROOTFS_B>"
if [ "${current_part_var}" = "A" ]; then
    current_part="${part_a}"
elif [ "${current_part_var}" = "B" ]; then
    current_part="${part_b}"
fi

as "Check if boot partition A exists" cukinia_test -b "/dev/disk/by-partlabel/<OTAB_LABEL_BOOT_A>"
as "Check if boot partition B exists" cukinia_test -b "/dev/disk/by-partlabel/<OTAB_LABEL_BOOT_B>"
as "Check if rootfs partition A exists" cukinia_test -b "${part_a}"
as "Check if rootfs partition B exists" cukinia_test -b "${part_b}"
as "Check if rwoverlay partition exists" cukinia_test -b "/dev/disk/by-partlabel/<OTAB_LABEL_ROOTFS_OVERLAY>"
as "Check if / is mounted as overlay" cukinia_test "$(df_source /)" = "overlay"
as "Check if /rofs is read-only" cukinia_cmd [[ "$(findmnt /rofs -n --output=options)" =~ '(^|,)ro(,|$)' ]]
as "Check if correct partition (${current_part_var}) is mounted on /rofs" \
    cukinia_test "$(realpath_df_source /rofs)" = "$(realpath_df_source ${current_part})"
as "Check if swupdate is configured to use efivar bootloader" \
    cukinia_test "$(get_swupdate_default_bootloader)" = "efivar"
