# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "otab-signed"
BBFILE_PATTERN_otab-signed = "^${LAYERDIR}/"
BBFILE_PRIORITY_otab-signed = "1"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_otab-signed = "1"

LAYERDEPENDS_otab-signed = " \
    otab-common \
    core \
    openembedded-layer \
    swupdate \
    "

LAYERSERIES_COMPAT_otab-signed = "honister kirkstone master"

## SWU image signing
#
# See: https://sbabic.github.io/swupdate/signed_images.html
#
SWU_SIG_KEY_FILE ??= "sig.key.pem"
SWU_SIG_CERT_FILE ??= "sig.cert.pem"
SWUPDATE_SIGNING ??= "CMS"
SWUPDATE_CMS_KEY ??= "${STAGING_DIR_TARGET}${OTAB_KEYS_DIR}/${SWU_SIG_KEY_FILE}"
SWUPDATE_CMS_CERT ??= "${STAGING_DIR_TARGET}${OTAB_KEYS_DIR}/${SWU_SIG_CERT_FILE}"

# otab script variables
OTAB_KEYS_DIR ??= "${datadir}"
OTAB_SIGNED_IMAGE = "true"
OTAB_SIG_CERT = "${SWU_SIG_CERT_FILE}"
