# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "otab-https"
BBFILE_PATTERN_otab-https = "^${LAYERDIR}/"
BBFILE_PRIORITY_otab-https = "6"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_otab-https = "1"

LAYERDEPENDS_otab-https = " \
    otab-common \
    core \
    openembedded-layer \
    swupdate \
    "

LAYERSERIES_COMPAT_otab-https = "scarthgap master"

# otab script variables
OTAB_SERVER_LINK ??= "https://example-server.com"
OTAB_BUCKET_PROD ??= "example-bucket"
OTAB_BUCKET_DEBUG ??= "example-bucket-debug"
OTAB_PASS_PROTECT ??= "no"
OTAB_HTTP_USER ??= "example-user"
OTAB_HTTP_PASSWORD ??= "example-password"

OTAB_UPDATE_SLOT_START ??= "08:00:00"
OTAB_UPDATE_SLOT_STOP ??= "12:00:00"

OTAB_SERVER_CERT_DIR_TARGET ??= "client"
OTAB_SERVER_CERT_FILE ??= "server.crt"
