# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "otab-uki"
BBFILE_PATTERN_otab-uki = "^${LAYERDIR}/"
BBFILE_PRIORITY_otab-uki = "6"

BBFILES_DYNAMIC += " \
    zarhus-bsp-x86_64:${LAYERDIR}/dynamic-layers/zarhus-bsp-x86_64/recipes-*/*/*.bb \
    zarhus-distro:${LAYERDIR}/dynamic-layers/zarhus-distro/recipes-*/*/*.bb \
"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_otab-uki = "1"

LAYERDEPENDS_otab-uki = " \
    otab-common \
    core \
    openembedded-layer \
    swupdate \
    "

LAYERSERIES_COMPAT_otab-uki = "scarthgap master"

##################################################
# OTAB variables
##################################################

WKS_FILE:x86-64 = "otab-uki-x86-uefi.wks.in"
OTAB_LABEL_BOOT_A ??= "boot_a"
OTAB_LABEL_BOOT_B ??= "boot_b"
OTAB_LABEL_ROOTFS_A ??= "rootfs_a"
OTAB_LABEL_ROOTFS_B ??= "rootfs_b"
OTAB_LABEL_ROOTFS_OVERLAY ??= "rwoverlay"
OTAB_LABEL_DATA ??= "data"

##################################################
# WKS rootfs-sed plugin variables
##################################################

# mount correct boot partition and set as read-only
FSTAB_A_SED=" \
    s|.*\(/boot .*\)|LABEL=${OTAB_LABEL_BOOT_A} \1| @ \
    s|\(.*/boot .*\) defaults\(.*\)|\1 defaults,ro\2| \
"
FSTAB_B_SED=" \
    s|.*\(/boot.*\)|LABEL=${OTAB_LABEL_BOOT_B} \1| @ \
    s|\(.*/boot .*\) defaults\(.*\)|\1 defaults,ro\2| \
"

# Generated with 'uuid -m' tool. Check
# dynamic-layers/zarhus-bsp-x86_64/recipes-zarhus/images/otab-uki.inc to see how
# to generate UUID based on repository commit
BOOT_A_UUID ??= "7d44af0e-412f-11f0-b434-43f24436bbef"
BOOT_B_UUID ??= "b32e6740-412f-11f0-a6ad-df732f388429"
ROOT_A_UUID ??= "b8a30442-412f-11f0-a7c2-d795d2926e45"
ROOT_B_UUID ??= "be43152c-412f-11f0-a99a-17f6567575ce"

WICVARS:append = " \
    FSTAB_A_SED FSTAB_B_SED BOOT_A_UUID BOOT_B_UUID ROOT_A_UUID ROOT_B_UUID \
"
