# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "otab-uki"
BBFILE_PATTERN_otab-uki = "^${LAYERDIR}/"
BBFILE_PRIORITY_otab-uki = "6"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_otab-uki = "1"

LAYERDEPENDS_otab-uki = " \
    otab-common \
    core \
    openembedded-layer \
    swupdate \
    "

LAYERSERIES_COMPAT_otab-uki = "scarthgap master"

##################################################
# OTAB variables
##################################################

WKS_FILE:x86-64 = "otab-uki-x86-uefi.wks.in"
OTAB_LABEL_BOOT_A ??= "boot_a"
OTAB_LABEL_BOOT_B ??= "boot_b"
OTAB_LABEL_ROOTFS_A ??= "rootfs_a"
OTAB_LABEL_ROOTFS_B ??= "rootfs_b"
OTAB_LABEL_ROOTFS_OVERLAY ??= "rwoverlay"
OTAB_LABEL_DATA ??= "data"
