# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "otab-encryption"
BBFILE_PATTERN_otab-encryption = "^${LAYERDIR}/"
BBFILE_PRIORITY_otab-encryption = "2"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_otab-encryption = "1"

LAYERDEPENDS_otab-encryption = " \
    otab-common \
    core \
    openembedded-layer \
    swupdate \
    "

LAYERSERIES_COMPAT_otab-encryption = "honister kirkstone master"


## SWU image encryption
#
# See: https://sbabic.github.io/swupdate/encrypted_images.html
#
SWUPDATE_AES_FILE ??= "${LAYERDIR}/recipes-otab/otab-keys-enc/enc.key"
SWUPDATE_ENCRYPT_SWDESC ??= "1"

SWU_ENC_KEY_FILE ??= "enc.key"

# otab script variables
OTAB_KEYS_DIR ??= "${datadir}"
OTAB_ENCRYPTED_IMAGE = "true"
OTAB_ENC_KEY = "enc.key"
