#!/bin/sh

wait_for_enter() {
    echo "Press Enter to continue..."
    read -r _ignore
}

error_check() {
    ret=$?
    err_msg="$1"
    if [ $ret != 0 ]; then
        fatal "$err_msg (err=$ret)"
    fi
}

# encrypt_device <device> [flags]
# generates new recovery password if encrypting for the first time, otherwise
# enrolls previous recovery key. flags can be set to no_reencrypt to encrypt
# device without in-place re-encryption. It's faster but overwrites whole
# filesystem
encrypt_device() {
    device_to_encrypt="$1"
    if [ "$2" = "no_reencrypt" ]; then
        reencrypt=
    else
        reencrypt="y"
    fi

    luks_label="luks_$(get_partition_partlabel "$device_to_encrypt")"
    # shellcheck disable=SC3040
    set -o pipefail

    echo "Preparing to encrypt $device_to_encrypt"
    umount "$device_to_encrypt" 2>/dev/null
    if [ -n "$reencrypt" ]; then
        device_size="$(lsblk -nbo SIZE "$device_to_encrypt")"
        e2fsck -fp "$device_to_encrypt" >/dev/null
        # reduce fs size to make space for LUKS2 header
        resize2fs "$device_to_encrypt" "$(($device_size/1024/1024-32))M" -f >/dev/null
        error_check "Failed to shrink filesystem"
    fi
    echo "Encrypting $device_to_encrypt"
    key="tmp_key"
    dd if=/dev/urandom of="$key" bs=512 count=4 2>/dev/null
    chmod 600 "$key"
    if [ -n "$reencrypt" ]; then
        echo "YES" | cryptsetup reencrypt \
            --encrypt --type luks2 --key-file "$key" \
            --reduce-device-size 32M "$device_to_encrypt"
    else
        echo "YES" | cryptsetup luksFormat --type luks2 --key-file "$key" "$device_to_encrypt"
    fi
    error_check "Encryption failed"
    cryptsetup config "$device_to_encrypt" --label "$luks_label"

    if [ -n "$RECOVERY_KEY" ]; then
        echo "Enrolling previously generated recovery key"
        cryptsetup luksAddKey --key-file="$key" "$device_to_encrypt" < "$RECOVERY_KEY"
        echo '{"type":"systemd-recovery","keyslots":["1"]}' |
            cryptsetup token import --key-file="$key" "$device_to_encrypt"
        error_check "Enrolling recovery key failed"
    else
        echo "Enrolling recovery key"
        RECOVERY_KEY=recovery_key
        systemd-cryptenroll --recovery-key --unlock-key-file="$key" \
            "$device_to_encrypt" >"$RECOVERY_KEY" 2>/dev/null
        error_check "Enrolling recovery key failed"
        # Copy of systemd-cryptenroll output
        cat <<EOF
A secret recovery key has been generated for this volume:

    🔐 $(cat "$RECOVERY_KEY")

Please save this secret recovery key at a secure location. It may be used to
regain access to the volume if the other configured access credentials have
been lost or forgotten. The recovery key may be entered in place of a password
whenever authentication is requested.
EOF
        wait_for_enter
    fi
    echo "Enrolling TPM device"
    systemd-cryptenroll --wipe-slot=password --unlock-key-file="$key" \
        --tpm2-device=auto --tpm2-pcrs="<PCRS>" "$device_to_encrypt"
    error_check "Enrolling TPM failed"

    cryptsetup open --token-only "$device_to_encrypt" "$luks_label"
    error_check "Couldn't decrypt $device_to_encrypt"
    if [ -n "$reencrypt" ]; then
        echo "n" | e2fsck -f -p "/dev/mapper/$luks_label" >/dev/null
        resize2fs "/dev/mapper/$luks_label" >/dev/null
    fi
    echo "Successfully encrypted $device_to_encrypt"

    # shellcheck disable=SC3040
    set +o pipefail
}

parse_bootparam_to_device() {
    param="$1"
    # Either PARTLABEL, PARTUUID or path to device
    if [ "$(echo "${param}" | cut -c1-9)" = "PARTUUID=" ]; then
        partuuid=$(echo "$param" | cut -c10-)
        param="/dev/disk/by-partuuid/$partuuid"
    elif [ "$(echo "${param}" | cut -c1-10)" = "PARTLABEL=" ]; then
        partlabel=$(echo "$param" | cut -c11-)
        param="/dev/disk/by-partlabel/$partlabel"
    fi
    echo "$param"
    if [ ! -b "$param" ]; then
        return 1
    fi
    return 0
}

get_partition_partlabel() {
    lsblk -no PARTLABEL "$1" | awk NF
}

encrypt_decrypt_enabled() {
	return 0
}

# Function uses 2 arguments.
# - rd.luks.rootfs=<PARTITION>
# - rd.luks.encrypt=<PARTITION>[,PARTITION]...
# where <PARTITION> can be either:
# - PARTLABEL=<PARTLABEL>
# - PARTUUID=<PARTUUID>
# - path to block device e.g. /dev/sda2
# Script first checks if rootfs is encrypted. If it isn't then it encrypts
# partitions in rd.luks.encrypt after that it encrypts rd.luks.rootfs.
# If rootfs is encrypted then it first decrypts rootfs and then all partitions
# in rd.luks.encrypt. Initramfs will try to continue booting even if partitions
# in rd.luks.encrypt couldn't be decrypted
encrypt_decrypt_run() {
    if [ -z "$bootparam_rd_luks_rootfs" ]; then
        return 0;
    fi

    rd_luks_rootfs="$(parse_bootparam_to_device "$bootparam_rd_luks_rootfs")"
    error_check "$rd_luks_rootfs doesn't exist or isn't block device"
    rootfs_luks_label="luks_$(get_partition_partlabel "$rd_luks_rootfs")"

    # if rootfs is already encrypted then only decrypt
    if cryptsetup isLuks "$rd_luks_rootfs" >/dev/null; then
        cryptsetup open "$rd_luks_rootfs" "$rootfs_luks_label"
        error_check "Couldn't decrypt $rd_luks_rootfs"

        # shellcheck disable=SC2154
        for decrypt in $(echo "$bootparam_rd_luks_encrypt" | tr ',' '\n'); do
            decrypt_part="$(echo "$decrypt" | cut -d'=' -f 1,2)"
            if ! decrypt_device=$(parse_bootparam_to_device "$decrypt_part"); then
                echo "$decrypt_device doesn't exist or isn't block device"
                continue
            fi
            luks_label="luks_$(get_partition_partlabel "$decrypt_device")"
            # skip already opened rootfs
            if [ "$rootfs_luks_label" = "$luks_label" ]; then
                continue
            fi
            if ! cryptsetup open "$decrypt_device" "$luks_label"; then
                echo "Couldn't decrypt $decrypt_device"
            fi
        done
        return 0
    fi

    RECOVERY_KEY=
    for encrypt in $(echo "$bootparam_rd_luks_encrypt" | tr ',' '\n'); do
        encrypt_part="$(echo "$encrypt" | cut -d'=' -f 1,2)"
        encrypt_flag="$(echo "$encrypt" | cut -d'=' -f 3)"
        encrypt_device=$(parse_bootparam_to_device "$encrypt_part")
        error_check "$encrypt_device doesn't exist or isn't block device"
        luks_label="luks_$(get_partition_partlabel "$encrypt_device")"
        # Let's encrypt rootfs at the end
        if [ "$rootfs_luks_label" = "$luks_label" ]; then
            continue
        fi
        encrypt_device "$encrypt_device" "$encrypt_flag"
        error_check "Couldn't encrypt $encrypt_device."
    done
    encrypt_device "$rd_luks_rootfs"
    error_check "Couldn't encrypt $rd_luks_rootfs."
}
