#!/bin/sh

echo_tty() {
    if [ -n "$1" ]; then
        echo "$1" | tee /dev/tty0
    else
        tee /dev/tty0
    fi
}

wait_for_enter() {
    pids=""
    ttys="$(grep -oE "console=[^ ,]*" /proc/cmdline | sed 's/console=//g' | sort | uniq)"
    echo_tty "Press Enter to continue..."
    for tty in $ttys; do
        if [ "$tty" != "tty0" ]; then
            # shellcheck disable=SC3061,SC2162
            read < "/dev/$tty" & pids="$pids $!"
        fi
    done
    # shellcheck disable=SC3061,SC2162
    read < "/dev/tty0" & pids="$pids $!"
    # shellcheck disable=SC3045
    wait -n
    # shellcheck disable=SC2086
    kill $pids 2>/dev/null
}

error_check() {
    ret=$?
    err_msg="$1"
    if [ $ret != 0 ]; then
        echo_tty "$err_msg (err=$ret)"
        fatal ""
    fi
}

# encrypt_device <device> [recovery_key]
# generates new recovery password if one isn't provided and saves to temporary
# recovery_key file so it can be used when encrypting more partitions
encrypt_device() {
    device_to_encrypt="$1"
    recovery_key="$2"

    luks_label="luks_$(lsblk -no PARTLABEL "$device_to_encrypt")"
    # shellcheck disable=SC3040
    set -o pipefail

    echo_tty "Preparing to encrypt $device_to_encrypt"
    umount "$device_to_encrypt" 2>/dev/null || true
    rootfs_size="$(lsblk -nbo SIZE "$device_to_encrypt")"
    e2fsck -fp "$device_to_encrypt" >/dev/null
    # reduce fs size to make space for LUKS2 header
    resize2fs "$device_to_encrypt" "$(($rootfs_size/1024/1024-32))M"
    error_check "Failed to shrink filesystem"

    echo_tty "Encrypting $device_to_encrypt"
    key="tmp_key"
    dd if=/dev/urandom of="$key" bs=512 count=4 2>/dev/null
    echo "YES" | cryptsetup reencrypt \
        --encrypt --type luks2 --key-file "$key" \
        --reduce-device-size 32M "$device_to_encrypt" | echo_tty
    error_check "Encryption failed"
    cryptsetup config "$device_to_encrypt" --label "$luks_label"

    if [ -n "$recovery_key" ]; then
        echo_tty "Enrolling previously generated recovery key"
        cryptsetup luksAddKey --key-file="$key" "$device_to_encrypt" < "$recovery_key"
        echo '{"type":"systemd-recovery","keyslots":["1"]}' |
            cryptsetup token import --key-file="$key" "$device_to_encrypt"
        error_check "Enrolling recovery key failed"
    else
        echo_tty "Enrolling recovery key"
        systemd-cryptenroll --recovery-key --unlock-key-file="$key" \
            "$device_to_encrypt" >recovery_key 2>/dev/null
        error_check "Enrolling recovery key failed"
        # Copy of systemd-cryptenroll output
        cat <<EOF | echo_tty
A secret recovery key has been generated for this volume:

    🔐 $(cat recovery_key)

Please save this secret recovery key at a secure location. It may be used to
regain access to the volume if the other configured access credentials have
been lost or forgotten. The recovery key may be entered in place of a password
whenever authentication is requested.
EOF
        wait_for_enter
    fi
    echo_tty "Enrolling TPM device"
    systemd-cryptenroll --wipe-slot=password --unlock-key-file="$key" \
        --tpm2-device=auto --tpm2-pcrs="<PCRS>" "$device_to_encrypt" | echo_tty
    error_check "Enrolling TPM failed"

    cryptsetup open --token-only "$device_to_encrypt" "$luks_label"
    error_check "Couldn't decrypt $device_to_encrypt"
    echo "n" | e2fsck -f -p "/dev/mapper/luks_rootfs"
    resize2fs "/dev/mapper/$luks_label"
    echo_tty "Successfully encrypted $device_to_encrypt"

    # shellcheck disable=SC3040
    set +o pipefail
}

encrypt_decrypt_enabled() {
	return 0
}

encrypt_decrypt_run() {
    # rd.luks.rootfs cmdline argument
    if [ -z "$bootparam_rd_luks_rootfs" ]; then
        return 0;
    fi

    rd_luks_rootfs="$bootparam_rd_luks_rootfs"
    # Either PARTLABEL, PARTUUID or path to device
    if [ "$(echo ${rd_luks_rootfs} | cut -c1-9)" = "PARTUUID=" ]; then
        root_partuuid=$(echo $rd_luks_rootfs | cut -c10-)
        rd_luks_rootfs="/dev/disk/by-partuuid/$root_partuuid"
    elif [ "$(echo ${rd_luks_rootfs} | cut -c1-10)" = "PARTLABEL=" ]; then
        root_partlabel=$(echo $rd_luks_rootfs | cut -c11-)
        rd_luks_rootfs="/dev/disk/by-partlabel/$root_partlabel"
    fi
    if [ ! -b "$rd_luks_rootfs" ]; then
        echo_tty "$rd_luks_rootfs doesn't exist or isn't block device"
        return 1
    fi

    luks_rootfs_label="luks_$(lsblk -no PARTLABEL "$rd_luks_rootfs")"

    # if rootfs is already encrypted then only decrypt
    if cryptsetup luksDump "$rd_luks_rootfs" >/dev/null 2>&1; then
        cryptsetup open "$rd_luks_rootfs" "$luks_rootfs_label"
        error_check "Couldn't decrypt $rd_luks_rootfs"
        return 0
    fi

    encrypt_device "$rd_luks_rootfs"
}
