#!/bin/sh

wait_for_enter() {
    echo "Press Enter to continue..."
    read -r _ignore
}

error_check() {
    ret=$?
    err_msg="$1"
    if [ $ret != 0 ]; then
        fatal "$err_msg (err=$ret)"
    fi
}

# encrypt_device <device> [recovery_key]
# generates new recovery password if one isn't provided and saves to temporary
# recovery_key file so it can be used when encrypting more partitions
encrypt_device() {
    device_to_encrypt="$1"

    luks_label="luks_$(lsblk -no PARTLABEL "$device_to_encrypt")"
    # shellcheck disable=SC3040
    set -o pipefail

    echo "Preparing to encrypt $device_to_encrypt"
    umount "$device_to_encrypt" 2>/dev/null
    device_size="$(lsblk -nbo SIZE "$device_to_encrypt")"
    e2fsck -fp "$device_to_encrypt" >/dev/null
    # reduce fs size to make space for LUKS2 header
    resize2fs "$device_to_encrypt" "$(($device_size/1024/1024-32))M" -f >/dev/null
    error_check "Failed to shrink filesystem"

    echo "Encrypting $device_to_encrypt"
    key="tmp_key"
    dd if=/dev/urandom of="$key" bs=512 count=4 2>/dev/null
    chmod 600 "$key"
    echo "YES" | cryptsetup reencrypt \
        --encrypt --type luks2 --key-file "$key" \
        --reduce-device-size 32M "$device_to_encrypt"
    error_check "Encryption failed"
    cryptsetup config "$device_to_encrypt" --label "$luks_label"

    if [ -n "$RECOVERY_KEY" ]; then
        echo "Enrolling previously generated recovery key"
        cryptsetup luksAddKey --key-file="$key" "$device_to_encrypt" < "$RECOVERY_KEY"
        echo '{"type":"systemd-recovery","keyslots":["1"]}' |
            cryptsetup token import --key-file="$key" "$device_to_encrypt"
        error_check "Enrolling recovery key failed"
    else
        echo "Enrolling recovery key"
        RECOVERY_KEY=recovery_key
        systemd-cryptenroll --recovery-key --unlock-key-file="$key" \
            "$device_to_encrypt" >"$RECOVERY_KEY" 2>/dev/null
        error_check "Enrolling recovery key failed"
        # Copy of systemd-cryptenroll output
        cat <<EOF
A secret recovery key has been generated for this volume:

    🔐 $(cat "$RECOVERY_KEY")

Please save this secret recovery key at a secure location. It may be used to
regain access to the volume if the other configured access credentials have
been lost or forgotten. The recovery key may be entered in place of a password
whenever authentication is requested.
EOF
        wait_for_enter
    fi
    echo "Enrolling TPM device"
    systemd-cryptenroll --wipe-slot=password --unlock-key-file="$key" \
        --tpm2-device=auto --tpm2-pcrs="<PCRS>" "$device_to_encrypt"
    error_check "Enrolling TPM failed"

    cryptsetup open --token-only "$device_to_encrypt" "$luks_label"
    error_check "Couldn't decrypt $device_to_encrypt"
    echo "n" | e2fsck -f -p "/dev/mapper/$luks_label" >/dev/null
    resize2fs "/dev/mapper/$luks_label" >/dev/null
    echo "Successfully encrypted $device_to_encrypt"

    # shellcheck disable=SC3040
    set +o pipefail
}

parse_bootparam_to_device() {
    param="$1"
    # Either PARTLABEL, PARTUUID or path to device
    if [ "$(echo "${param}" | cut -c1-9)" = "PARTUUID=" ]; then
        partuuid=$(echo "$param" | cut -c10-)
        param="/dev/disk/by-partuuid/$partuuid"
    elif [ "$(echo "${param}" | cut -c1-10)" = "PARTLABEL=" ]; then
        partlabel=$(echo "$param" | cut -c11-)
        param="/dev/disk/by-partlabel/$partlabel"
    fi
    echo "$param"
    if [ ! -b "$param" ]; then
        return 1
    fi
    return 0
}

encrypt_decrypt_enabled() {
	return 0
}

# Function uses 2 arguments.
# - rd.luks.rootfs=<PARTITION>
# - rd.luks.encrypt=<PARTITION>[,PARTITION]...
# where <PARTITION> can be either:
# - PARTLABEL=<PARTLABEL>
# - PARTUUID=<PARTUUID>
# - path to block device e.g. /dev/sda2
# Script first checks if rootfs is encrypted. If it isn't then it encrypts
# partitions in rd.luks.encrypt after that it encrypts rd.luks.rootfs.
# If rootfs is encrypted then it first decrypts rootfs and then all partitions
# in rd.luks.encrypt. Initramfs will try to continue booting even if partitions
# in rd.luks.encrypt couldn't be decrypted
encrypt_decrypt_run() {
    if [ -z "$bootparam_rd_luks_rootfs" ]; then
        return 0;
    fi

    rd_luks_rootfs="$(parse_bootparam_to_device "$bootparam_rd_luks_rootfs")"
    error_check "$rd_luks_rootfs doesn't exist or isn't block device"
    rootfs_luks_label="luks_$(lsblk -no PARTLABEL "$rd_luks_rootfs")"

    # if rootfs is already encrypted then only decrypt
    if cryptsetup isLuks "$rd_luks_rootfs" >/dev/null; then
        cryptsetup open "$rd_luks_rootfs" "$rootfs_luks_label"
        error_check "Couldn't decrypt $rd_luks_rootfs"

        # shellcheck disable=SC2154
        for decrypt in $(echo "$bootparam_rd_luks_encrypt" | tr ',' '\n'); do
            if ! decrypt_device=$(parse_bootparam_to_device "$decrypt"); then
                echo "$decrypt_device doesn't exist or isn't block device"
                continue
            fi
            luks_label="luks_$(lsblk -no PARTLABEL "$decrypt_device")"
            # already decrypted
            if cryptsetup status "$luks_label" >/dev/null; then
                continue
            fi
            if ! cryptsetup open "$decrypt_device" "$luks_label"; then
                echo "Couldn't decrypt $decrypt_device"
            fi
        done
        return 0
    fi

    RECOVERY_KEY=
    for encrypt in $(echo "$bootparam_rd_luks_encrypt" | tr ',' '\n'); do
        encrypt_device=$(parse_bootparam_to_device "$encrypt")
        error_check "$encrypt_device doesn't exist or isn't block device"
        luks_label="luks_$(lsblk -no PARTLABEL "$encrypt_device")"
        # Let's encrypt rootfs at the end
        if [ "$rootfs_luks_label" = "$luks_label" ]; then
            continue
        fi
        encrypt_device "$encrypt_device"
        error_check "Couldn't encrypt $encrypt_device."
    done
    encrypt_device "$rd_luks_rootfs"
    error_check "Couldn't encrypt $encrypt_device."
}
