#!/bin/sh

error_check() {
    ret=$?
    err_msg="$1"
    if [ $ret != 0 ]; then
        fatal "$err_msg (err=$ret)"
    fi
}

create_overlay_fs_enabled() {
	return 0
}

# create rwoverlay partition on first boot.
create_overlay_fs_run() {
    partition="/dev/disk/by-label/<OTAB_LABEL_ROOTFS_OVERLAY>"
    if [ -b "$partition" ]; then
        return 0
    else
        partition="/dev/mapper/luks_<OTAB_LABEL_ROOTFS_OVERLAY>"
    fi
    # shellcheck disable=SC3040
    set -o pipefail
    echo "Creating <OTAB_LABEL_ROOTFS_OVERLAY> ext4 filesystem"
    mkfs.ext4 -qFL "<OTAB_LABEL_ROOTFS_OVERLAY>" "$partition"
    error_check "Failed to create ext4 filesystem on $partition"
    # shellcheck disable=SC3040
    set +o pipefail
}
